language: node_js
node_js: stable
git:
  depth: false
branches:
  only:
    - src

# S: Build Lifecycle
install:
  - yarn

script:
  - yarn build

after_success:
  - cd ./dist
  - git init
  - git config user.name "${youdeliang}"
  - git config user.email "${1048726003@qq.com}"
  - git add .
  - git commit -m "Build $(date +%Y%m%d%H%M)"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master:master
# E: Build LifeCycle