language: node_js # node环境
node_js: lts/*
install:
  - yarn
script:
  - yarn build # 执行命令
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # travis服务上的token变量
  target-branch: master # 集成发布到master上
  keep-history: true
  on:
    branch: master